<script>
  import HomePageContainer from "../containers/HomePageContainer/index.svelte";
</script>

<style type="text/scss">

</style>

<svelte:head>
  <title>My Store</title>
</svelte:head>

<HomePageContainer>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
  <div>This is my home page laksnj</div>
</HomePageContainer>
